//
// File generated by /usr/local/root_v5.34.21_enableall/bin/rootcint at Wed Feb 11 15:21:47 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ReconSelector_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ReconSelector_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void SelfAwaySelector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_SelfAwaySelector(void *p = 0);
   static void *newArray_SelfAwaySelector(Long_t size, void *p);
   static void delete_SelfAwaySelector(void *p);
   static void deleteArray_SelfAwaySelector(void *p);
   static void destruct_SelfAwaySelector(void *p);
   static void streamer_SelfAwaySelector(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::SelfAwaySelector*)
   {
      ::SelfAwaySelector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::SelfAwaySelector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("SelfAwaySelector", ::SelfAwaySelector::Class_Version(), "./SelfAwaySelector.h", 27,
                  typeid(::SelfAwaySelector), DefineBehavior(ptr, ptr),
                  &::SelfAwaySelector::Dictionary, isa_proxy, 0,
                  sizeof(::SelfAwaySelector) );
      instance.SetNew(&new_SelfAwaySelector);
      instance.SetNewArray(&newArray_SelfAwaySelector);
      instance.SetDelete(&delete_SelfAwaySelector);
      instance.SetDeleteArray(&deleteArray_SelfAwaySelector);
      instance.SetDestructor(&destruct_SelfAwaySelector);
      instance.SetStreamerFunc(&streamer_SelfAwaySelector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::SelfAwaySelector*)
   {
      return GenerateInitInstanceLocal((::SelfAwaySelector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::SelfAwaySelector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr SelfAwaySelector::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *SelfAwaySelector::Class_Name()
{
   return "SelfAwaySelector";
}

//______________________________________________________________________________
const char *SelfAwaySelector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SelfAwaySelector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int SelfAwaySelector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::SelfAwaySelector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void SelfAwaySelector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SelfAwaySelector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *SelfAwaySelector::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::SelfAwaySelector*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void SelfAwaySelector::Streamer(TBuffer &R__b)
{
   // Stream an object of class SelfAwaySelector.

   TSelector::Streamer(R__b);
}

//______________________________________________________________________________
void SelfAwaySelector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class SelfAwaySelector.
      TClass *R__cl = ::SelfAwaySelector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fChain", &fChain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_eventID", &od_eventID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_gps_fine", &od_gps_fine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_gps_coarse", &od_gps_coarse);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_timestamp", &od_timestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_nclusters", &od_nclusters);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_wt_charge", &od_wt_charge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_charge", &od_cluster_charge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_start", &od_cluster_start);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_height", &od_cluster_height);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_multiplicity", &od_cluster_multiplicity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_pass_multcut", &od_cluster_pass_multcut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*od_cluster_dtprompt", &od_cluster_dtprompt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_eventID", &b_od_eventID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_gps_fine", &b_od_gps_fine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_gps_coarse", &b_od_gps_coarse);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_timestamp", &b_od_timestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_nclusters", &b_od_nclusters);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_wt_charge", &b_od_wt_charge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_charge", &b_od_cluster_charge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_start", &b_od_cluster_start);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_height", &b_od_cluster_height);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_multiplicity", &b_od_cluster_multiplicity);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_pass_multcut", &b_od_cluster_pass_multcut);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*b_od_cluster_dtprompt", &b_od_cluster_dtprompt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_gps_hist", &nv_all_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_ene_hist", &nv_all_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_small_ene_hist", &nv_all_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_gps_ene_hist", &nv_all_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_ntuple", &nv_all_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_all_charge_height_multiplicity_hist", &nv_all_charge_height_multiplicity_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_fail_gps_hist", &nv_fail_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_fail_ene_hist", &nv_fail_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_fail_small_ene_hist", &nv_fail_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_fail_gps_ene_hist", &nv_fail_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_fail_ntuple", &nv_fail_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gps_hist", &nv_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_ene_hist", &nv_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_small_ene_hist", &nv_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gps_ene_hist", &nv_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_ntuple", &nv_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_charge_height_multiplicity_hist", &nv_charge_height_multiplicity_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_full_ene_hist", &nv_gamma_full_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_full_small_ene_hist", &nv_gamma_full_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_coincidence_gps_hist", &nv_gamma_coincidence_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_coincidence_ene_hist", &nv_gamma_coincidence_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_coincidence_small_ene_hist", &nv_gamma_coincidence_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_coincidence_gps_ene_hist", &nv_gamma_coincidence_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_coincidence_ntuple", &nv_gamma_coincidence_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_prompt_gps_hist", &nv_gamma_prompt_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_prompt_ene_hist", &nv_gamma_prompt_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_prompt_small_ene_hist", &nv_gamma_prompt_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_prompt_gps_ene_hist", &nv_gamma_prompt_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_prompt_ntuple", &nv_gamma_prompt_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_delay_gps_hist", &nv_gamma_delay_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_delay_ene_hist", &nv_gamma_delay_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_delay_small_ene_hist", &nv_gamma_delay_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_delay_gps_ene_hist", &nv_gamma_delay_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_delay_ntuple", &nv_gamma_delay_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_after_gps_hist", &nv_gamma_after_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_after_ene_hist", &nv_gamma_after_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_after_small_ene_hist", &nv_gamma_after_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_after_gps_ene_hist", &nv_gamma_after_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_after_ntuple", &nv_gamma_after_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_first_gps_hist", &nv_gamma_first_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_first_ene_hist", &nv_gamma_first_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_first_small_ene_hist", &nv_gamma_first_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_first_gps_ene_hist", &nv_gamma_first_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_first_ntuple", &nv_gamma_first_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_late_gps_hist", &nv_gamma_late_gps_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_late_ene_hist", &nv_gamma_late_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_late_small_ene_hist", &nv_gamma_late_small_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_late_gps_ene_hist", &nv_gamma_late_gps_ene_hist);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nv_gamma_late_ntuple", &nv_gamma_late_ntuple);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*id", &id);
      TSelector::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_SelfAwaySelector(void *p) {
      return  p ? new(p) ::SelfAwaySelector : new ::SelfAwaySelector;
   }
   static void *newArray_SelfAwaySelector(Long_t nElements, void *p) {
      return p ? new(p) ::SelfAwaySelector[nElements] : new ::SelfAwaySelector[nElements];
   }
   // Wrapper around operator delete
   static void delete_SelfAwaySelector(void *p) {
      delete ((::SelfAwaySelector*)p);
   }
   static void deleteArray_SelfAwaySelector(void *p) {
      delete [] ((::SelfAwaySelector*)p);
   }
   static void destruct_SelfAwaySelector(void *p) {
      typedef ::SelfAwaySelector current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_SelfAwaySelector(TBuffer &buf, void *obj) {
      ((::SelfAwaySelector*)obj)->::SelfAwaySelector::Streamer(buf);
   }
} // end of namespace ROOT for class ::SelfAwaySelector

/********************************************************
* ReconSelector_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableReconSelector_dict();

extern "C" void G__set_cpp_environmentReconSelector_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("SelfAwaySelector.h");
  G__cpp_reset_tagtableReconSelector_dict();
}
#include <new>
extern "C" int G__cpp_dllrevReconSelector_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* SelfAwaySelector */
static int G__ReconSelector_dict_579_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   SelfAwaySelector* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new SelfAwaySelector((TTree*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) SelfAwaySelector((TTree*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SelfAwaySelector[n];
       } else {
         p = new((void*) gvp) SelfAwaySelector[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new SelfAwaySelector;
       } else {
         p = new((void*) gvp) SelfAwaySelector;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) SelfAwaySelector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SelfAwaySelector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) SelfAwaySelector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SelfAwaySelector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((SelfAwaySelector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SelfAwaySelector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SelfAwaySelector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) SelfAwaySelector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ReconSelector_dict_579_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) SelfAwaySelector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef SelfAwaySelector G__TSelfAwaySelector;
static int G__ReconSelector_dict_579_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (SelfAwaySelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((SelfAwaySelector*) (soff+(sizeof(SelfAwaySelector)*i)))->~G__TSelfAwaySelector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (SelfAwaySelector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((SelfAwaySelector*) (soff))->~G__TSelfAwaySelector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* SelfAwaySelector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncReconSelector_dict {
 public:
  G__Sizep2memfuncReconSelector_dict(): p(&G__Sizep2memfuncReconSelector_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncReconSelector_dict::*p)();
};

size_t G__get_sizep2memfuncReconSelector_dict()
{
  G__Sizep2memfuncReconSelector_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceReconSelector_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector))) {
     SelfAwaySelector *G__Lderived;
     G__Lderived=(SelfAwaySelector*)0x1000;
     {
       TSelector *G__Lpbase=(TSelector*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector),G__get_linked_tagnum(&G__ReconSelector_dictLN_TSelector),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector),G__get_linked_tagnum(&G__ReconSelector_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableReconSelector_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* SelfAwaySelector */
static void G__setup_memvarSelfAwaySelector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector));
   { SelfAwaySelector *p; p=(SelfAwaySelector*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fChain)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TTree),-1,-1,1,"fChain=",0,"!pointer to the analyzed TTree or TChain");
   G__memvar_setup((void*)((long)(&p->od_eventID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"od_eventID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_gps_fine)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_gps_fine=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_gps_coarse)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_gps_coarse=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_timestamp)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_timestamp=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_nclusters)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"od_nclusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_wt_charge)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_wt_charge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_charge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"od_cluster_charge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_start)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"od_cluster_start=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_height)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"od_cluster_height=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_multiplicity)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"od_cluster_multiplicity=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_pass_multcut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,1,"od_cluster_pass_multcut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_dtprompt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"od_cluster_dtprompt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->b_od_eventID)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_eventID=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_gps_fine)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_gps_fine=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_gps_coarse)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_gps_coarse=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_timestamp)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_timestamp=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_nclusters)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_nclusters=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_wt_charge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_wt_charge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_charge)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_charge=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_start)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_start=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_height)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_height=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_multiplicity)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_multiplicity=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_pass_multcut)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_pass_multcut=",0,"!");
   G__memvar_setup((void*)((long)(&p->b_od_cluster_dtprompt)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TBranch),-1,-1,1,"b_od_cluster_dtprompt=",0,"!");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_all_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_all_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_all_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_all_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_all_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_all_charge_height_multiplicity_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_fail_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_fail_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_fail_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_fail_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_fail_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_charge_height_multiplicity_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_full_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_full_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_coincidence_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_coincidence_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_coincidence_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_coincidence_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_coincidence_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_prompt_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_prompt_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_prompt_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_prompt_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_prompt_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_delay_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_delay_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_delay_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_delay_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_delay_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_after_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_after_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_after_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_after_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_after_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_first_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_first_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_first_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_first_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_first_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_late_gps_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_late_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"nv_gamma_late_small_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH2F),-1,-1,4,"nv_gamma_late_gps_ene_hist=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TNtuple),-1,-1,4,"nv_gamma_late_ntuple=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TH1F),-1,-1,4,"id=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarReconSelector_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncSelfAwaySelector(void) {
   /* SelfAwaySelector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector));
   G__memfunc_setup("SelfAwaySelector",1629,G__ReconSelector_dict_579_0_1, 105, G__get_linked_tagnum(&G__ReconSelector_dictLN_SelfAwaySelector), -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 '0' -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Version",742,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Begin",485,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveBegin",992,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Init",404,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TTree' - 0 - tree", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Notify",633,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "n - 'Long64_t' 0 - entry", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetEntry",818,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetOption",933,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - option", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetObject",899,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInputList",1240,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "U 'TList' - 0 - input", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetOutputList",1357,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SlaveTerminate",1444,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Terminate",937,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("BookHistograms",1452,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillHistograms",1448,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ReconSelector_dict_579_0_17, 85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&SelfAwaySelector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ReconSelector_dict_579_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SelfAwaySelector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ReconSelector_dict_579_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&SelfAwaySelector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ReconSelector_dict_579_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&SelfAwaySelector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ReconSelector_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ReconSelector_dict_579_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ReconSelector_dict_579_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SelfAwaySelector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ReconSelector_dict_579_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SelfAwaySelector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ReconSelector_dict_579_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&SelfAwaySelector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ReconSelector_dict_579_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&SelfAwaySelector::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~SelfAwaySelector", 1755, G__ReconSelector_dict_579_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncReconSelector_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalReconSelector_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcReconSelector_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ReconSelector_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TBranch = { "TBranch" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TSelector = { "TSelector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TH1F = { "TH1F" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TH2F = { "TH2F" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_TNtuple = { "TNtuple" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_SelfAwaySelector = { "SelfAwaySelector" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableReconSelector_dict() {
  G__ReconSelector_dictLN_TClass.tagnum = -1 ;
  G__ReconSelector_dictLN_TBuffer.tagnum = -1 ;
  G__ReconSelector_dictLN_TMemberInspector.tagnum = -1 ;
  G__ReconSelector_dictLN_TObject.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TList.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TTree.tagnum = -1 ;
  G__ReconSelector_dictLN_TBranch.tagnum = -1 ;
  G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TSelector.tagnum = -1 ;
  G__ReconSelector_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__ReconSelector_dictLN_TH1F.tagnum = -1 ;
  G__ReconSelector_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__ReconSelector_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__ReconSelector_dictLN_TH2F.tagnum = -1 ;
  G__ReconSelector_dictLN_TNtuple.tagnum = -1 ;
  G__ReconSelector_dictLN_SelfAwaySelector.tagnum = -1 ;
  G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableReconSelector_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TList);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TTree);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TBranch);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TSelector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TH1F);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TH2F);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_TNtuple);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_SelfAwaySelector),sizeof(SelfAwaySelector),-1,29952,(char*)NULL,G__setup_memvarSelfAwaySelector,G__setup_memfuncSelfAwaySelector);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ReconSelector_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupReconSelector_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupReconSelector_dict()");
  G__set_cpp_environmentReconSelector_dict();
  G__cpp_setup_tagtableReconSelector_dict();

  G__cpp_setup_inheritanceReconSelector_dict();

  G__cpp_setup_typetableReconSelector_dict();

  G__cpp_setup_memvarReconSelector_dict();

  G__cpp_setup_memfuncReconSelector_dict();
  G__cpp_setup_globalReconSelector_dict();
  G__cpp_setup_funcReconSelector_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncReconSelector_dict();
  return;
}
class G__cpp_setup_initReconSelector_dict {
  public:
    G__cpp_setup_initReconSelector_dict() { G__add_setup_func("ReconSelector_dict",(G__incsetup)(&G__cpp_setupReconSelector_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initReconSelector_dict() { G__remove_setup_func("ReconSelector_dict"); }
};
G__cpp_setup_initReconSelector_dict G__cpp_setup_initializerReconSelector_dict;

