//
// File generated by /usr/local/root_v5.34.21_enableall/bin/rootcint at Thu Feb  5 15:14:48 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Alpha_SelfDST_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Alpha_SelfDST_dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::VetoEvent VetoEvent;
      #else
      class VetoEvent  {
         public:
         //friend XX;
         int od_eventID; //
         int od_nclusters; //
         double od_gps_fine; //
         double od_gps_coarse; //
         double od_timestamp; //[us]                                                                                                  
         double od_tpc_timestamp_diff; //[us]
         double od_wt_charge; //
         vector< Double_t > od_cluster_charge; //[PE]                                                                                   
         vector< Double_t > od_cluster_start; //[us]                                                                                
         vector< Double_t > od_cluster_height; //
         vector< Double_t > od_cluster_multiplicity; //
         vector< Int_t > od_cluster_pass_multcut; //
         vector< Double_t > od_cluster_dtprompt; //[us]                                                                          
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void VetoEvent_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void VetoEvent_Dictionary();
   static void *new_VetoEvent(void *p = 0);
   static void *newArray_VetoEvent(Long_t size, void *p);
   static void delete_VetoEvent(void *p);
   static void deleteArray_VetoEvent(void *p);
   static void destruct_VetoEvent(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::VetoEvent*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::VetoEvent) == sizeof(::ROOT::Shadow::VetoEvent));
      ::VetoEvent *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::VetoEvent),0);
      static ::ROOT::TGenericClassInfo 
         instance("VetoEvent", "./Alpha_SelfDST.C", 48,
                  typeid(::VetoEvent), DefineBehavior(ptr, ptr),
                  &VetoEvent_ShowMembers, &VetoEvent_Dictionary, isa_proxy, 4,
                  sizeof(::VetoEvent) );
      instance.SetNew(&new_VetoEvent);
      instance.SetNewArray(&newArray_VetoEvent);
      instance.SetDelete(&delete_VetoEvent);
      instance.SetDeleteArray(&deleteArray_VetoEvent);
      instance.SetDestructor(&destruct_VetoEvent);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::VetoEvent*)
   {
      return GenerateInitInstanceLocal((::VetoEvent*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::VetoEvent*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void VetoEvent_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::VetoEvent*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void VetoEvent_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class VetoEvent.
      typedef ::ROOT::Shadow::VetoEvent ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::VetoEvent*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_eventID", &sobj->od_eventID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_nclusters", &sobj->od_nclusters);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_gps_fine", &sobj->od_gps_fine);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_gps_coarse", &sobj->od_gps_coarse);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_timestamp", &sobj->od_timestamp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_tpc_timestamp_diff", &sobj->od_tpc_timestamp_diff);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_wt_charge", &sobj->od_wt_charge);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_charge", (void*)&sobj->od_cluster_charge);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->od_cluster_charge, "od_cluster_charge.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_start", (void*)&sobj->od_cluster_start);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->od_cluster_start, "od_cluster_start.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_height", (void*)&sobj->od_cluster_height);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->od_cluster_height, "od_cluster_height.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_multiplicity", (void*)&sobj->od_cluster_multiplicity);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->od_cluster_multiplicity, "od_cluster_multiplicity.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_pass_multcut", (void*)&sobj->od_cluster_pass_multcut);
      R__insp.InspectMember("vector<Int_t>", (void*)&sobj->od_cluster_pass_multcut, "od_cluster_pass_multcut.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "od_cluster_dtprompt", (void*)&sobj->od_cluster_dtprompt);
      R__insp.InspectMember("vector<Double_t>", (void*)&sobj->od_cluster_dtprompt, "od_cluster_dtprompt.", false);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_VetoEvent(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::VetoEvent : new ::VetoEvent;
   }
   static void *newArray_VetoEvent(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::VetoEvent[nElements] : new ::VetoEvent[nElements];
   }
   // Wrapper around operator delete
   static void delete_VetoEvent(void *p) {
      delete ((::VetoEvent*)p);
   }
   static void deleteArray_VetoEvent(void *p) {
      delete [] ((::VetoEvent*)p);
   }
   static void destruct_VetoEvent(void *p) {
      typedef ::VetoEvent current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::VetoEvent

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "/usr/local/root_v5.34.21_enableall/lib/root/cint/cint/lib/prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<int>

/********************************************************
* Alpha_SelfDST_dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAlpha_SelfDST_dict();

extern "C" void G__set_cpp_environmentAlpha_SelfDST_dict() {
  G__cpp_reset_tagtableAlpha_SelfDST_dict();
}
#include <new>
extern "C" int G__cpp_dllrevAlpha_SelfDST_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* VetoEvent */
static int G__Alpha_SelfDST_dict_656_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   VetoEvent* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new VetoEvent[n];
     } else {
       p = new((void*) gvp) VetoEvent[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new VetoEvent;
     } else {
       p = new((void*) gvp) VetoEvent;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Alpha_SelfDST_dict_656_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   VetoEvent* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new VetoEvent(*(VetoEvent*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef VetoEvent G__TVetoEvent;
static int G__Alpha_SelfDST_dict_656_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (VetoEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((VetoEvent*) (soff+(sizeof(VetoEvent)*i)))->~G__TVetoEvent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (VetoEvent*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((VetoEvent*) (soff))->~G__TVetoEvent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Alpha_SelfDST_dict_656_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   VetoEvent* dest = (VetoEvent*) G__getstructoffset();
   *dest = *(VetoEvent*) libp->para[0].ref;
   const VetoEvent& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* VetoEvent */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAlpha_SelfDST_dict {
 public:
  G__Sizep2memfuncAlpha_SelfDST_dict(): p(&G__Sizep2memfuncAlpha_SelfDST_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAlpha_SelfDST_dict::*p)();
};

size_t G__get_sizep2memfuncAlpha_SelfDST_dict()
{
  G__Sizep2memfuncAlpha_SelfDST_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAlpha_SelfDST_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAlpha_SelfDST_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* VetoEvent */
static void G__setup_memvarVetoEvent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent));
   { VetoEvent *p; p=(VetoEvent*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->od_eventID)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"od_eventID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_nclusters)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"od_nclusters=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_gps_fine)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_gps_fine=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_gps_coarse)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_gps_coarse=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_timestamp)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_timestamp=",0,"[us]                                                                                                  ");
   G__memvar_setup((void*)((long)(&p->od_tpc_timestamp_diff)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_tpc_timestamp_diff=",0,"[us]");
   G__memvar_setup((void*)((long)(&p->od_wt_charge)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"od_wt_charge=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_charge)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"od_cluster_charge=",0,"[PE]                                                                                   ");
   G__memvar_setup((void*)((long)(&p->od_cluster_start)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"od_cluster_start=",0,"[us]                                                                                ");
   G__memvar_setup((void*)((long)(&p->od_cluster_height)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"od_cluster_height=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_multiplicity)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"od_cluster_multiplicity=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_pass_multcut)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<Int_t>"),-1,1,"od_cluster_pass_multcut=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->od_cluster_dtprompt)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<Double_t>"),-1,1,"od_cluster_dtprompt=",0,"[us]                                                                          ");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarAlpha_SelfDST_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncVetoEvent(void) {
   /* VetoEvent */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent));
   G__memfunc_setup("VetoEvent",928,G__Alpha_SelfDST_dict_656_0_1, 105, G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("VetoEvent", 928, G__Alpha_SelfDST_dict_656_0_2, (int) ('i'), G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent), -1, 0, 1, 1, 1, 0, "u 'VetoEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~VetoEvent", 1054, G__Alpha_SelfDST_dict_656_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Alpha_SelfDST_dict_656_0_4, (int) ('u'), G__get_linked_tagnum(&G__Alpha_SelfDST_dictLN_VetoEvent), -1, 1, 1, 1, 1, 0, "u 'VetoEvent' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAlpha_SelfDST_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAlpha_SelfDST_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAlpha_SelfDST_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_VetoEvent = { "VetoEvent" , 115 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAlpha_SelfDST_dict() {
  G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_VetoEvent.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAlpha_SelfDST_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_VetoEvent),sizeof(VetoEvent),-1,262400,(char*)NULL,G__setup_memvarVetoEvent,G__setup_memfuncVetoEvent);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__Alpha_SelfDST_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupAlpha_SelfDST_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupAlpha_SelfDST_dict()");
  G__set_cpp_environmentAlpha_SelfDST_dict();
  G__cpp_setup_tagtableAlpha_SelfDST_dict();

  G__cpp_setup_inheritanceAlpha_SelfDST_dict();

  G__cpp_setup_typetableAlpha_SelfDST_dict();

  G__cpp_setup_memvarAlpha_SelfDST_dict();

  G__cpp_setup_memfuncAlpha_SelfDST_dict();
  G__cpp_setup_globalAlpha_SelfDST_dict();
  G__cpp_setup_funcAlpha_SelfDST_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAlpha_SelfDST_dict();
  return;
}
class G__cpp_setup_initAlpha_SelfDST_dict {
  public:
    G__cpp_setup_initAlpha_SelfDST_dict() { G__add_setup_func("Alpha_SelfDST_dict",(G__incsetup)(&G__cpp_setupAlpha_SelfDST_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAlpha_SelfDST_dict() { G__remove_setup_func("Alpha_SelfDST_dict"); }
};
G__cpp_setup_initAlpha_SelfDST_dict G__cpp_setup_initializerAlpha_SelfDST_dict;

